
export interface CBO {
  code: string;
  title: string;
}

export const CBO_LIST: CBO[] = [
  { code: '7152-10', title: 'Pedreiro' },
  { code: '7170-20', title: 'Servente de obras' },
  { code: '7155-05', title: 'Carpinteiro' },
  { code: '7156-15', title: 'Eletricista de instalações' },
  { code: '7241-10', title: 'Encanador' },
  { code: '7153-05', title: 'Armador de estrutura de concreto' },
  { code: '7166-10', title: 'Pintor de obras' },
  { code: '7164-05', title: 'Gesseiro' },
  { code: '7165-10', title: 'Assentador de revestimentos cerâmicos' },
  { code: '4110-10', title: 'Assistente administrativo' },
  { code: '9144-05', title: 'Mecânico de manutenção de automóveis, motocicletas e veículos similares' },
  { code: '1231-05', title: 'Diretor administrativo' },
  { code: '7152-30', title: 'Pedreiro de edificações' },
  { code: '7155-25', title: 'Carpinteiro de obras' },
  { code: '7155-35', title: 'Carpinteiro de fôrmas para concreto' },
  { code: '7156-10', title: 'Eletricista de instalações (edifícios)' },
  { code: '7241-15', title: 'Encanador industrial' },
  { code: '7153-15', title: 'Armador de estrutura de concreto armado' },
  { code: '7233-15', title: 'Pintor de estruturas metálicas' },
  { code: '9511-05', title: 'Eletricista' },
  { code: '9111-10', title: 'Mecânico de manutenção de bombas' },
  { code: '9131-10', title: 'Mecânico de manutenção de equipamento de mineração' },
  { code: '5143-10', title: 'Auxiliar de manutenção predial' },
  { code: '5142-15', title: 'Varredor de rua' },
  { code: '5143-30', title: 'Limpador de piscinas' },
  { code: '5161-05', title: 'Barbeiro' },
  { code: '5134-05', title: 'Garçom' },
  { code: '5136-10', title: 'Pizzaiolo' },
  { code: '5136-15', title: 'Sushiman' },
  { code: '5132-05', title: 'Cozinheiro geral' },
  { code: '5173-30', title: 'Vigilante' },
  { code: '5174-10', title: 'Porteiro' },
  { code: '5174-20', title: 'Vigia' },
  { code: '7102-05', title: 'Mestre (construção civil)' },
  { code: '7201-15', title: 'Mestre de ferramentaria' },
  { code: '7201-10', title: 'Mestre de caldeiraria' },
  { code: '7701-10', title: 'Mestre carpinteiro' },
  { code: '7244-40', title: 'Serralheiro' },
  { code: '7243-15', title: 'Soldador' },
  { code: '7212-15', title: 'Fresador (fresadora universal)' },
  { code: '7214-10', title: 'Operador de fresadora com comando numérico' },
  { code: '7214-30', title: 'Operador de torno com comando numérico' },
  { code: '7122-05', title: 'Cortador de pedras' },
  { code: '7122-20', title: 'Polidor de pedras' },
  { code: '7161-05', title: 'Acabador de superfícies de concreto' },
  { code: '7152-05', title: 'Calceteiro' },
  { code: '7165-35', title: 'Taqueiro' },
  { code: '7165-30', title: 'Mosaísta' },
  { code: '7165-40', title: 'Rejuntador de revestimentos' },
  { code: '7157-10', title: 'Instalador de isolantes acústicos' },
  { code: '7157-15', title: 'Instalador de isolantes térmicos (refrigeração e climatização)' },
  { code: '7157-20', title: 'Instalador de isolantes térmicos de caldeira e tubulações' },
  { code: '7157-25', title: 'Instalador de material isolante, a mão (edificações)' },
  { code: '7157-30', title: 'Instalador de material isolante, à máquina (edificações)' },
  { code: '7154-15', title: 'Operador de central de concreto' },
  { code: '7154-05', title: 'Operador de betoneira' },
  { code: '7154-10', title: 'Operador de bomba de concreto' },
  { code: '7151-15', title: 'Operador de escavadeira' },
  { code: '7151-35', title: 'Operador de pá carregadeira' },
  { code: '7151-30', title: 'Operador de motoniveladora' },
  { code: '7151-10', title: 'Operador de compactadora de solos' },
  { code: '7151-20', title: 'Operador de máquina de abrir valas' },
  { code: '7151-25', title: 'Operador de máquinas de construção civil e mineração' },
  { code: '7151-40', title: 'Operador de pavimentadora (asfalto, concreto e materiais similares)' },
  { code: '7151-45', title: 'Operador de trator de lâmina' },
  { code: '7112-45', title: 'Operador de trator (minas e pedreiras)' },
  { code: '7112-25', title: 'Operador de máquina perfuradora (minas e pedreiras)' },
  { code: '7112-30', title: 'Operador de máquina perfuratriz' },
  { code: '7112-10', title: 'Operador de carregadeira' },
  { code: '7112-15', title: 'Operador de máquina cortadora (minas e pedreiras)' },
  { code: '7112-20', title: 'Operador de máquina de extração contínua (minas de carvão)' },
  { code: '7111-30', title: 'Mineiro' },
  { code: '7111-05', title: 'Amostrador de minérios' },
  { code: '7111-10', title: 'Canteiro' },
  { code: '7111-15', title: 'Aparelhador de pedra (mina)' },
  { code: '7111-20', title: 'Detonador' },
  { code: '7111-25', title: 'Escorador de minas' },
  { code: '7113-15', title: 'Sondador (poços de petróleo e gás)' },
  { code: '7113-20', title: 'Sondador de poços (exceto de petróleo e gás)' },
  { code: '7113-10', title: 'Sondador de poços tubulares e sistemas rotativos' },
  { code: '7113-25', title: 'Plataformista (petróleo)' },
  { code: '7113-30', title: 'Torrista (petróleo)' },
  { code: '7113-05', title: 'Operador de sonda de percussão' }
];
